### ISSUE TITLE
Learn and use version control systems

### ISSUE THREAD

**Issue by dharanisenthil** [foss-cloud-computing-practicals/backlogs#1]
## User Story

As a B.Tech IT final year student, I want to familiarise myself with the use of github.com as the version control system , so that I can organise my software development projects related to my course and my personal learning and
showcase my work to others and be ready to face the software industry with the needed professional skills.

### Acceptance Criteria

- [x] Created an org  and repository in github.com
- [x] Maintained the readme.md file describing the purpose of my repository
- [ ] Protect your repository from direct commits to master
- [x] Describe what is four eye principle
- [x] Describe what is boy scout rule
- [x] Define few clean code practices
- [ ] Created a simple Java Spring Boot application to manage advertisements and maintained the source code in my repository

**Comment by saisundu** [comment]
- [x] Describe four eye principle in the context of source code management with github
- [x] Boy scout rule and an example in coding
